SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_TRACK_MODIFICATIONS = True
DEBUG = True
SECRET_KEY = '1werw3@#$@#%$^%&^%&^*&(*(()3he6'
BABEL_DEFAULT_LOCALE = 'zh_Hans_CN'

UPLOAD_FOLDER = './upload/'
MAX_CONTENT_LENGTH = 16 * 1024 * 1024